// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var container = CssJs.style([
      CssJs.display("flex"),
      CssJs.gap({
            NAME: "px",
            VAL: 8
          }),
      CssJs.justifyContent("spaceBetween"),
      CssJs.alignItems("center"),
      CssJs.border({
            NAME: "px",
            VAL: 1
          }, "solid", CssJs.rgba(0, 0, 0, {
                NAME: "percent",
                VAL: 20
              })),
      CssJs.borderRadius({
            NAME: "px",
            VAL: 3
          }),
      CssJs.height({
            NAME: "px",
            VAL: 26
          }),
      CssJs.background({
            NAME: "hex",
            VAL: "fff"
          })
    ]);

var Styles = {
  container: container
};

function Button(Props) {
  var onClick = Props.onClick;
  var onKeyDown = Props.onKeyDown;
  var itemRight = Props.itemRight;
  var children = Props.children;
  var tmp = {
    className: container
  };
  if (onKeyDown !== undefined) {
    tmp.onKeyDown = Caml_option.valFromOption(onKeyDown);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("button", tmp, children, Belt_Option.mapWithDefault(itemRight, null, (function (el) {
                    return React.createElement("div", undefined, el);
                  })));
}

var make = Button;

export {
  Styles ,
  make ,
  
}
/* container Not a pure module */
