// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactSelect from "../../../bindings/ReactSelect/ReactSelect.mjs";
import ReactSelect$1 from "react-select";
import List from "react-virtualized/dist/commonjs/List";
import AutoSizer from "react-virtualized/dist/commonjs/AutoSizer";

var className = CssJs.style([
      CssJs.position("absolute"),
      CssJs.marginTop({
            NAME: "px",
            VAL: 8
          }),
      CssJs.borderRadius({
            NAME: "px",
            VAL: 4
          }),
      CssJs.backgroundColor({
            NAME: "hex",
            VAL: "ffffff"
          }),
      CssJs.zIndex(2)
    ]);

function Select$Menu(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className
            }, children);
}

var Menu = {
  className: className,
  make: Select$Menu
};

var className$1 = CssJs.style([
      CssJs.top("zero"),
      CssJs.right("zero"),
      CssJs.bottom("zero"),
      CssJs.left("zero"),
      CssJs.position("fixed"),
      CssJs.zIndex(1)
    ]);

function Select$Backdrop(Props) {
  var onClick = Props.onClick;
  return React.createElement("div", {
              className: className$1,
              onClick: onClick
            });
}

var Backdrop = {
  className: className$1,
  make: Select$Backdrop
};

var className$2 = CssJs.style([CssJs.position("relative")]);

function Select$Dropdown(Props) {
  var children = Props.children;
  var isOpen = Props.isOpen;
  var target = Props.target;
  var onClose = Props.onClose;
  return React.createElement("div", {
              className: className$2
            }, target, isOpen ? React.createElement(Select$Menu, {
                    children: children
                  }) : null, isOpen ? React.createElement(Select$Backdrop, {
                    onClick: onClose
                  }) : null);
}

var Dropdown = {
  className: className$2,
  make: Select$Dropdown
};

function Select$Svg(Props) {
  var className = Props.className;
  var children = Props.children;
  var tmp = {
    role: "presentation",
    height: "32",
    width: "32",
    focusable: "false",
    viewBox: "-8 -8 24 24"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, children);
}

var Svg = {
  make: Select$Svg
};

var className$3 = CssJs.style([
      CssJs.color({
            NAME: "var",
            VAL: "tomato"
          }),
      CssJs.height({
            NAME: "px",
            VAL: -24
          }),
      CssJs.height({
            NAME: "px",
            VAL: -32
          })
    ]);

function Select$DropdownIndicator(Props) {
  return React.createElement("div", {
              className: className$3
            }, React.createElement(Select$Svg, {
                  children: React.createElement("path", {
                        clipRule: "evenodd",
                        d: "M10 5C10 6.01927 9.69501 6.96731 9.17131 7.75783L12.47 11.06L11.06 12.47L7.75786 9.17129C6.96734 9.695 6.01929 10 5 10C2.23858 10 0 7.76142 0 5C0 2.23858 2.23858 0 5 0C7.76142 0 10 2.23858 10 5ZM5 8.2C6.76731 8.2 8.2 6.76731 8.2 5C8.2 3.23269 6.76731 1.8 5 1.8C3.23269 1.8 1.8 3.23269 1.8 5C1.8 6.76731 3.23269 8.2 5 8.2Z",
                        fill: "#333333",
                        fillRule: "evenodd"
                      })
                }));
}

var DropdownIndicator = {
  className: className$3,
  make: Select$DropdownIndicator
};

var className$4 = CssJs.style([CssJs.marginRight({
            NAME: "px",
            VAL: -6
          })]);

function Select$ChevronDown(Props) {
  return React.createElement(Select$Svg, {
              className: className$4,
              children: React.createElement("path", {
                    d: "M8.292 10.293a1.009 1.009 0 0 0 0 1.419l2.939 2.965c.218.215.5.322.779.322s.556-.107.769-.322l2.93-2.955a1.01 1.01 0 0 0 0-1.419.987.987 0 0 0-1.406 0l-2.298 2.317-2.307-2.327a.99.99 0 0 0-1.406 0z",
                    fill: "currentColor",
                    fillRule: "evenodd"
                  })
            });
}

var ChevronDown = {
  className: className$4,
  make: Select$ChevronDown
};

function Select(Props) {
  var autoFocus = Props.autoFocus;
  var backspaceRemovesValue = Props.backspaceRemovesValue;
  var className = Props.className;
  var controlShouldRenderValue = Props.controlShouldRenderValue;
  var formatOptionLabel = Props.formatOptionLabel;
  var hideSelectedOptions = Props.hideSelectedOptions;
  var isClearable = Props.isClearable;
  var onChange = Props.onChange;
  var options = Props.options;
  var value = Props.value;
  var match = React.useState(function () {
        return false;
      });
  var setIsOpen = match[1];
  var toggleOpen = function (param) {
    return Curry._1(setIsOpen, (function (isOpen) {
                  return !isOpen;
                }));
  };
  var onSelectChange = function (newValue) {
    Curry._1(setIsOpen, (function (isOpen) {
            return !isOpen;
          }));
    return Curry._1(onChange, (newValue == null) ? undefined : Caml_option.some(newValue));
  };
  var components = React.useMemo((function () {
          return ReactSelect.createComponents((function (param) {
                        var focusedOption = param.focusedOption;
                        var children = param.children;
                        var rowCount = Array.isArray(children) ? children.length : 0;
                        var focusedOptionIndex = Array.isArray(children) ? children.findIndex(function (thisChild) {
                                return Caml_obj.caml_equal(thisChild.props.data, focusedOption);
                              }) : 0;
                        return React.createElement(AutoSizer, {
                                    children: (function (param) {
                                        return React.createElement(List, {
                                                    rowRenderer: (function (param) {
                                                        var index = param.index;
                                                        return React.createElement("div", {
                                                                    key: index.toString(),
                                                                    style: param.style
                                                                  }, Array.isArray(children) ? Caml_array.get(children, index) : children);
                                                      }),
                                                    rowHeight: (function (param) {
                                                        return 35;
                                                      }),
                                                    height: 200,
                                                    scrollToIndex: focusedOptionIndex > 0 ? focusedOptionIndex : 0,
                                                    width: param.width,
                                                    rowCount: rowCount
                                                  });
                                      }),
                                    disableHeight: true
                                  });
                      }), (function (param) {
                        return null;
                      }), (function (param) {
                        return React.createElement(Select$DropdownIndicator, {});
                      }), (function (param) {
                        return null;
                      }), undefined);
        }), []);
  var tmp = {
    components: components,
    formatOptionLabel: formatOptionLabel,
    menuIsOpen: true,
    onChange: onSelectChange,
    options: options,
    placeholder: "Search",
    styles: {
      control: (function (provided) {
          return Object.assign({}, provided, {
                      height: "35px",
                      marginBottom: "8px",
                      width: "370px",
                      flexDirection: "row-reverse"
                    });
        }),
      menu: (function (param) {
          return {
                  boxShadow: "inset 0 1px 0 rgba(0, 0, 0, 0.1)"
                };
        })
    }
  };
  if (autoFocus !== undefined) {
    tmp.autoFocus = autoFocus;
  }
  if (backspaceRemovesValue !== undefined) {
    tmp.backspaceRemovesValue = backspaceRemovesValue;
  }
  if (className !== undefined) {
    tmp.className = className;
  }
  if (controlShouldRenderValue !== undefined) {
    tmp.controlShouldRenderValue = controlShouldRenderValue;
  }
  if (hideSelectedOptions !== undefined) {
    tmp.hideSelectedOptions = hideSelectedOptions;
  }
  if (isClearable !== undefined) {
    tmp.isClearable = isClearable;
  }
  if (value !== undefined) {
    tmp.value = Caml_option.valFromOption(value);
  }
  return React.createElement("div", undefined, React.createElement(Select$Dropdown, {
                  children: React.createElement(ReactSelect$1, tmp),
                  isOpen: match[0],
                  target: React.createElement("button", {
                        onClick: toggleOpen
                      }, Curry._1(formatOptionLabel, value)),
                  onClose: toggleOpen
                }));
}

var make = Select;

export {
  Menu ,
  Backdrop ,
  Dropdown ,
  Svg ,
  DropdownIndicator ,
  ChevronDown ,
  make ,
  
}
/* className Not a pure module */
