// Generated by ReScript, PLEASE EDIT WITH CARE


var sm_s = String(8);

var Spacing = {
  sm: 8,
  sm_s: sm_s,
  sm_2: 16,
  sm_3: 24,
  sm_4: 32
};

var sm_s$1 = String(4);

var Radius = {
  sm: 4,
  sm_s: sm_s$1
};

export {
  Spacing ,
  Radius ,
  
}
/* sm_s Not a pure module */
