// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Client from "react-dom/client";

var app = document.querySelector("#app");

if (app == null) {
  Js_exn.raiseError("No id #app found");
} else {
  Client.createRoot(app).render(React.createElement("div", undefined, "Country Select"));
}

var app$1 = (app == null) ? undefined : Caml_option.some(app);

export {
  app$1 as app,
  
}
/* app Not a pure module */
