// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as CountrySelect from "../CountrySelect/CountrySelect.mjs";
import * as Client from "react-dom/client";

var rootElement = document.querySelector("#app");

if (rootElement == null) {
  Js_exn.raiseError("No id #app found");
} else {
  Client.createRoot(rootElement).render(React.createElement(CountrySelect.make, {
            onChange: (function (newCountry) {
                console.log(newCountry);
                
              }),
            country: "us",
            className: "custom-class"
          }));
}

var rootElement$1 = (rootElement == null) ? undefined : Caml_option.some(rootElement);

export {
  rootElement$1 as rootElement,
  
}
/* rootElement Not a pure module */
