// Generated by ReScript, PLEASE EDIT WITH CARE


function checkHasOptions(children) {
  if (Array.isArray(children)) {
    return children;
  }
  
}

var ChildrenOptions = {
  checkHasOptions: checkHasOptions
};

function createComponents(menuList, clearIndicator, dropdownIndicator, indicatorSeparator, noOptionsMessage, param) {
  return {
          MenuList: menuList,
          DropdownIndicator: dropdownIndicator,
          IndicatorSeparator: indicatorSeparator,
          ClearIndicator: clearIndicator,
          NoOptionsMessage: noOptionsMessage
        };
}

export {
  ChildrenOptions ,
  createComponents ,
  
}
/* No side effect */
