// Generated by ReScript, PLEASE EDIT WITH CARE


function createComponents(menuList, clearIndicator, dropdownIndicator, indicatorSeparator, param) {
  return {
          MenuList: menuList,
          DropdownIndicator: dropdownIndicator,
          IndicatorSeparator: indicatorSeparator,
          ClearIndicator: clearIndicator
        };
}

export {
  createComponents ,
  
}
/* No side effect */
