// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Select from "../common/Select/Select.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as CountryHook from "../../hooks/CountryHook.mjs";

function renderCountryLabel(optionCountry) {
  if (optionCountry !== undefined) {
    return React.createElement("div", undefined, React.createElement("span", {
                    className: "fi fi-" + optionCountry.value
                  }), React.createElement("span", undefined, optionCountry.label));
  } else {
    return "Select a Country";
  }
}

function CountrySelect(Props) {
  var onChange = Props.onChange;
  var value = Props.value;
  var className = Props.className;
  var countriesState = CountryHook.use(undefined);
  if (typeof countriesState === "number") {
    if (countriesState !== 0) {
      return React.createElement("div", undefined, "Something went wrong :(");
    } else {
      return React.createElement("div", undefined, "Fetching...");
    }
  }
  var tmp = {
    autoFocus: true,
    backspaceRemovesValue: true,
    controlShouldRenderValue: false,
    formatOptionLabel: renderCountryLabel,
    hideSelectedOptions: false,
    isClearable: true,
    onChange: onChange,
    options: countriesState._0,
    value: value
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement(Select.make, tmp);
}

var make = CountrySelect;

export {
  renderCountryLabel ,
  make ,
  
}
/* react Not a pure module */
