// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CountryHook from "../../hooks/CountryHook.mjs";
import ReactSelect from "react-select";

function CountrySelect(Props) {
  var countriesState = CountryHook.use(undefined);
  if (typeof countriesState === "number") {
    if (countriesState !== 0) {
      return React.createElement("div", undefined, "Something went wrong :(");
    } else {
      return React.createElement("div", undefined, "Fetching...");
    }
  } else {
    return React.createElement(ReactSelect, {
                options: countriesState._0,
                searchable: true,
                formatOptionLabel: (function (thisOption) {
                    return React.createElement("div", undefined, thisOption.label);
                  })
              });
  }
}

var make = CountrySelect;

export {
  make ,
  
}
/* react Not a pure module */
